### ISSUE TITLE
Change the CSS 

### ISSUE THREAD

**Issue by Deepankar1484** [HariomGupta123/hactoberfest2023#21]
Hey @HariomGupta123 , Hope you are doing great.
May i can help you in changing or updating the CSS of the page.
please assign me the issue and make it hacktoberfest 2023 labeled

**Comment by SamridhiNancy** [comment]
Hey man, i am an open source student kindly assign me the task

**Comment by saseentharan** [comment]
Hello! I'm interested in working on this task. I'm eager to contribute. Please consider assigning this to me @saseentharan, and I'll get started right away. Thanks! I will make a worthful contribution.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me under hactoberfest

**Comment by Kedarnath-Rothe** [comment]
Please review my PR and Merge Under hactoberfest
